export const events = [
  {
    id: "creatorWS",
    title: "Creator's Workshop",
    date: "31st March 2026",
    time: "5PM-8PM",
    about: "Intro to UI/UX and graphic design using Figma. Covers typography, colour theory, and layout design through hands-on exercises. Good prep for Negative Space.",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
    href: "/events/creatorWS",
    requiresPass: false,
    registered: false,
    prizePool: 0,
    venue: "AB5 - 205",
  },
  {
    id: "modelerWS",
    title: "ML Unlocked",
    date: "1st April 2026",
    time: "5PM-8PM",
    about: "Covers ML fundamentals (supervised/unsupervised learning, reinforcement learning, transformers) with hands-on exercises. Tailored to prep participants for Enigma.",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
    href: "/events/modelerWS",
    requiresPass: false,
    registered: false,
    prizePool: 0,
    venue: "AB5 - 205",
  },
  {
    id: "negSpace",
    title: "Negative Space",
    date: "1st April 2026",
    time: "7PM(1st April)-7PM(2nd April)",
    about: "Team design competition (2-3 members) around a surprise problem statement. Any medium allowed, judged on creativity and relevance.",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
    href: "/events/modelerWS",
    requiresPass: false,
    registered: false,
    prizePool: 6000,
    venue: "Online",
  },
  {
    id: "devWS",
    title: "Dev's Workshop",
    date: "2nd April 2026",
    time: "5PM-8PM",
    about: "Intro to React for building interactive web apps, ending with deployment via GitHub and Vercel.",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
    href: "/events/devWS",
    requiresPass: false,
    registered: false,
    prizePool: 0,
    venue: "AB5 - 205",
  },
  {
    id: "enigma",
    title: "Enigma",
    date: "2nd April 2026",
    time: "7PM(2nd April)-1AM(3rd April)",
    about: "4-hour solo Kaggle-style ML competition. Build models on real-world datasets and climb a live leaderboard ranked by accuracy.",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
    href: "/events/enigma",
    requiresPass: true,
    registered: false,
    prizePool: 7500,
    venue: "AB5 - 205",
  },
  {
    id: "techQuiz",
    title: "TechQuiz(IECSE X LDQ)",
    date: "3rd April 2026",
    time: "10AM-1PM",
    about: "A technical quiz conducted in collaboration with the LDQ",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
    href: "/events/techQuiz",
    requiresPass: false,
    registered: false,
    prizePool: 2250,
    venue: "AB5 - 205",
  },
  {
    id: "ooc",
    title: "Order Of Chaos",
    date: "3rd April 2026",
    time: "3PM-5PM",
    about: "Solo coding contest with 20 problems. Earn points by solving questions, challenge others to typing duels, and spend points in a shop.",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
    href: "/events/ooc",
    requiresPass: true,
    registered: false,
    prizePool: 7500,
    venue: "AB5 - 205",
  },
  {
    id: "nearProtocol",
    title: "IronClaw by NEAR Protocol",
    date: "4th April 2026",
    time: "5PM-8PM",
    about: "Talk + networking session by ArQ and one of the founder of NEAR Protocol on the NEAR Protocol cryptocurrency, followed by food.",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
    href: "/events/nearProtocol",
    requiresPass: false,
    registered: false,
    prizePool: 0,
    venue: "AB5 - 205",
  },
];
