export const events = [
  {
    id: "creatorWS",
    title: "Creator's Workshop",
    date: "30th March 2026",
    time: "5PM-8PM",
    about: "Wanna make Figma designs? join here",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
    href: "/events/creatorWS",
    requiresPass: false,
    registered: false,
    prizePool: 0,
  },
  {
    id: "devWS",
    title: "Dev's Workshop",
    date: "31st March 2026",
    time: "5PM-8PM",
    about: "Wanna give figma a life? join this",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
    href: "/events/devWS",
    requiresPass: false,
    registered: false,
    prizePool: 0,
  },
  {
    id: "modelerWS",
    title: "Modeler's Workshop",
    date: "1st April 2026",
    time: "5PM-8PM",
    about: "Wanna give the site a mind? join this",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
    href: "/events/modelerWS",
    requiresPass: false,
    registered: false,
    prizePool: 0,
  },
  {
    id: "enigma",
    title: "Enigma",
    date: "2nd April 2026",
    time: "5PM-8PM",
    about: "A Kaggle competition",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
    href: "/events/enigma",
    requiresPass: true,
    registered: false,
    prizePool: 7500,
  },
  {
    id: "techQuiz",
    title: "TechQuiz(IECSE X LDQ)",
    date: "3rd April 2026",
    time: "10AM-1PM",
    about: "A quiz on tech",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
    href: "/events/techQuiz",
    requiresPass: false,
    registered: false,
    prizePool: 2250,
  },
  {
    id: "ooc",
    title: "Order Of Chaos",
    date: "3rd April 2026",
    time: "3PM-5PM",
    about: "A coding competition with a twist",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
    href: "/events/ooc",
    requiresPass: true,
    registered: false,
    prizePool: 7500,
  },
  {
    id: "nearProtocol",
    title: "Near Protocol",
    date: "4th April 2026",
    time: "5PM-8PM",
    about: "Whatever this is",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
    href: "/events/nearProtocol",
    requiresPass: false,
    registered: false,
    prizePool: 0,
  },
];
